### ISSUE TITLE
Liteweight JSON document database framework targets

### ISSUE THREAD

**Issue by mwpowellhtx** [Unconcurrent/SoloDB#1]
Hello,

I am curious to use something like a [_MartenDB_](https://martendb.io/, but not especially keen on the [_Postgres_](https://postgresql.org) requirement. For this application, I am looking for a liteweight database like `SQLite`.

I found your package on _NuGet_, but I also noticed it is only targeting [`net8.0`](https://nuget.org/packages/SoloDB). Maybe there is a good reason why that is the case, but I wonder a layer such as data, database, serialization, could (indeed should) that not at least make the effort to target `netstandard`? Preferably `netstandard2.0`, as I think that seems to be the bare minimum LTS these days, of prior version if possible. Worst case `netstandard2.1`.

That being stated without having reviewed your code too deeply yet. Would be curious if a simple multi-target thought experiment would do the trick, and with what opportunities to pare back API surface area.

Food for thought, was just curious. Cheers thanks... 🍻

**Comment by mwpowellhtx** [comment]
Just reviewing couple of the known [_referenced package dependencies_](https://nuget.org/packages/SoloDB#dependencies-body-tab), you may be able to get away with a `netstandard2.0` target and be _"okay"_. I do not know that much about [`F#`](https://fsharp.org/learn) mind you, but at least from a dotnet evaluation perspective, FWIW...

* [`System.Data.SqlClient`](https://nuget.org/packages/System.Data.SqlClient/#supportedframeworks-body-tab)
* [`Dapper`](https://nuget.org/packages/Dapper/#supportedframeworks-body-tab)
* [`Microsoft.Data.Sqlite`](https://nuget.org/packages/Microsoft.Data.Sqlite/#supportedframeworks-body-tab)
* [`FSharp.Core`](https://nuget.org/packages/FSharp.Core/#supportedframeworks-body-tab)
* [`FSharp.Interop.Dynamic`](https://nuget.org/packages/FSharp.Interop.Dynamic/#supportedframeworks-body-tab)
* [`SQLitePCLRaw.bundle_e_sqlite3`](https://nuget.org/packages/SQLitePCLRaw.bundle_e_sqlite3/#supportedframeworks-body-tab)

There is nothing about any of these dependencies that needs to be `net8.0`, from what I can tell, they can all support `netstandard2.0`.

**Comment by Unconcurrent** [comment]
Hello,

Thank you for your interest in my project. This is primarily a learning project that I created for my own use and decided to publish for others who might find it useful. It is similar to MartenDB but intended for lighter projects.

The decision to target net8.0 instead of netstandard is not due to dependencies. The newer .NET versions offer numerous features and optimizations that netstandard does not provide. For example, netstandard requires a full Stream for something as simple as `SHA1.HashData(byte array)`, lacks the vast majority of `Span<>` methods, and does not support `NativeMemory`, among other limitations.

Even MartenDB only supports [newer .NET versions](https://martendb.io/introduction.html#net-version-compatibility) (6 to 8 at the time of writing).

While you can theoretically downgrade your framework API or use compiler-time `#IFs` to achieve compatibility with netstandard, it is not necessary for my needs. However, you are welcome to fork the project and modify it to suit your requirements.

**Comment by mwpowellhtx** [comment]
Ah yes I do see that now that you mention it in from [`Marten 6.0.0`](https://nuget.org/packages/Marten/6.0.0#supportedframeworks-body-tab) forward it seems. I am not an `F#` guy, per se, as I mentioned... would you mind enumerating those areas? I will consider then submitting a PR. So the challenges with `netstandard2.0` being what it is, even `netstandard2.1`; although admitedly 'end of life' which is unfortunate IMO, as this was a chief concern raised during the stand ups, and which Microsoft PM were a bit dodgy over the alusion.

However all that being the case, I generally consider data and serialization to be a building block layer, and do not like to commit to runtimes targets, until the last possible moment. In my case I am targeting `net8.0` `WPF`, but if I wanted to pivot, to an API or web, or a _Blazor_, or _cross-plat_, or whatever, what then; perhaps partly my ignorance on the landscape and roadmap, paths forward.

Not fully sold on the path forward there, may or may not personally submit PR, will give it some time for me to research a bit more and consider.

**Comment by mwpowellhtx** [comment]
In terms of nearest competitors, while not really in the JSON or document database _"space"_ as it were, still fairly traditionally relational ORM, [`NHibernate`](https://nuget.org/packages/NHibernate/5.5.2#supportedframeworks-body-tab), by contrast, does still, presumably multi-target `netstandard2.0` and so on. Have not reviewed the code there for specific preprocessor branching.

**Comment by Unconcurrent** [comment]
It is done sir, moved to netstandard 2.0 (257bdd7), I also published it on NuGet.

**Comment by mwpowellhtx** [comment]
WOW nice... and the potential audience increases as well. Not half bad.
